/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth - Send OTP
         * @description > You can send OTP through 3 times in 2 minutes
         */
        post: operations["v1.auth.send-code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth - Verify OTP
         * @description This method verifies the provided code for the given mobile address.
         *     If valid, it authenticates the user and returns a JWT token.
         *
         *     > You can verify OTP through 5 times in 1 minute
         */
        post: operations["v1.auth.verify-code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout user (revoke the token)
         * @description This method will be used to revoke the JWT token and logout the user.
         *     It will return a JSON response with a success message.
         */
        post: operations["v1.auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticated User - Show
         * @description This method will be used to return the authenticated user.
         *     It will return a JSON response with the user data.
         */
        post: operations["v1.auth.user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/broadcasting/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authenticate the request for channel access */
        get: operations["broadcast.authenticate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthenticationTokenTypeEnum
         * @enum {string}
         */
        AuthenticationTokenTypeEnum: "bearer" | "api_key";
        /** SendCodeRequest */
        SendCodeRequest: {
            /** @example 09175918439 */
            mobile: string;
        };
        /** TokenResource */
        TokenResource: {
            authentication_type: Record<string, never>;
            access_token: string;
            token_type: Record<string, never>;
        };
        /** UserResource */
        UserResource: {
            id: string;
            first_name: string | null;
            last_name: string | null;
            name: string;
            mobile: string;
            is_mobile_verified: boolean;
            avatar_url: string;
        };
        /** VerifyCodeRequest */
        VerifyCodeRequest: {
            /** @example 09175918439 */
            mobile: string;
            code: string;
        };
    };
    responses: {
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "v1.auth.send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendCodeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Verification code sent successfully";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.auth.verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeRequest"];
            };
        };
        responses: {
            /** @description `TokenResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TokenResource"];
                    } | Record<string, never>;
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Authentication failed";
                    } | {
                        /** @enum {string} */
                        message: "Invalid or expired verification code";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return a JSON response with a success message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Successfully logged out";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.auth.user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return a JSON response with the user data
             *
             *
             *
             *     `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "broadcast.authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
}
